.github/PULL_REQUEST_TEMPLATE.md
.pre-commit-config.yaml
{{ cookiecutter.project_name }}/.github/PULL_REQUEST_TEMPLATE.md
{{ cookiecutter.project_name }}/.pre-commit-config.yaml
{{ cookiecutter.project_name }}/pyproject.toml

Update `pyupgrade` to 2.4.1 in inner project

update pyupgrade to 2.4.1

---

.github/PULL_REQUEST_TEMPLATE.md
.github/release-drafter.yml
.github/workflows/release-drafter.yml
{{ cookiecutter.project_name }}/.github/PULL_REQUEST_TEMPLATE.md
{{ cookiecutter.project_name }}/.github/release-drafter.yml
{{ cookiecutter.project_name }}/.github/workflows/release-drafter.yml

- Added usage for [`Release drafter`](https://github.com/release-drafter/release-drafter) action
N/A

added release drafter

---

{{ cookiecutter.project_name }}/pyproject.toml
{{ cookiecutter.project_name }}/{{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_') }}/__init__.py
{{ cookiecutter.project_name }}/{{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_') }}/__main__.py

- Added functionality for the example `--version` flag
N/A

added `version` to examples

---

.editorconfig
.github/PULL_REQUEST_TEMPLATE.md
.github/release-drafter.yml
.github/workflows/build.yml
Makefile
README.md
cookiecutter.json
hooks/post_gen_project.py
{{ cookiecutter.project_name }}/.editorconfig
{{ cookiecutter.project_name }}/.github/PULL_REQUEST_TEMPLATE.md
{{ cookiecutter.project_name }}/.github/release-drafter.yml
{{ cookiecutter.project_name }}/.github/workflows/build.yml
{{ cookiecutter.project_name }}/CHANGELOG.md
{{ cookiecutter.project_name }}/CONTRIBUTING.md
{{ cookiecutter.project_name }}/README.md
{{ cookiecutter.project_name }}/cookiecutter-config-file.yml

- Big documentation update
- Added saved context in `cookiecutter-config-file.yml`
N/A

`v0.1.0` pre-release

---

.github/release-drafter.yml
{{ cookiecutter.project_name }}/.github/release-drafter.yml

- Now all `dependencies` labels will be stored separately in releases.

group dependencies

---

README.md
{{ cookiecutter.project_name }}/README.md

- Added link to gitmoji
- Update some emojis in README
N/A

:lipstick: added link to gitmoji

---

.github/release-drafter.yml
README.md
{{ cookiecutter.project_name }}/.github/release-drafter.yml
{{ cookiecutter.project_name }}/README.md

- Update `README.md` for Releases
N/A

:wrench: update release-drafter config

---

README.md
{{ cookiecutter.project_name }}/README.md

- Updated grammar in the `README.md` files
- Added new awesome libraries to `Packages`
- Added [Cookiecutter Data Science Template: `cdst`](https://github.com/crplab/cdst) to `Credits`
- Added autogenerated year in `Citation`
N/A

:pencil2: update grammar in readme

---

.dependabot/config.yml
{{ cookiecutter.project_name }}/.dependabot/config.yml
{{ cookiecutter.project_name }}/pyproject.toml

- Added config files for `dependabot`
- Update `pytest` version for the inner project
N/A

:pushpin: update dependabot configs

---

.dependabot/config.yml

:ambulance: hotfix for dependabot

---

README.md
{{ cookiecutter.project_name }}/README.md

:speech_balloon: Added label tables to the README

---

README.md
{{ cookiecutter.project_name }}/.dockerignore
{{ cookiecutter.project_name }}/README.md

:see_no_evil: added .dockerignore

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/security.md
.github/PULL_REQUEST_TEMPLATE.md
README.md
SECURITY.md
{{ cookiecutter.project_name }}/.github/ISSUE_TEMPLATE/config.yml
{{ cookiecutter.project_name }}/.github/ISSUE_TEMPLATE/security.md
{{ cookiecutter.project_name }}/.github/PULL_REQUEST_TEMPLATE.md
{{ cookiecutter.project_name }}/README.md
{{ cookiecutter.project_name }}/SECURITY.md

- Added `SECURITY.md`
- Added `security` issue template

:lock: added SECURITY.md and configs

---

{{ cookiecutter.project_name }}/pyproject.toml

- Added missing `pre-commit` dependency

:heavy_plus_sign: added missing dependency

---

README.md

- Added a table to show `Input variables`

:lipstick: added a table to show `Input variables`

---

.pre-commit-config.yaml
setup.cfg
{{ cookiecutter.project_name }}/.pre-commit-config.yaml
{{ cookiecutter.project_name }}/pyproject.toml
{{ cookiecutter.project_name }}/setup.cfg

:zap: Upgraged mypy config

---

README.md

:lipstick: added asciinema demo

---

{{ cookiecutter.project_name }}/pyproject.toml
{{ cookiecutter.project_name }}/{{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_') }}/__main__.py

:fire: updated example

---

.pre-commit-config.yaml
Makefile
README.md
hooks/post_gen_project.py
poetry.lock
pyproject.toml
{{ cookiecutter.project_name }}/.pre-commit-config.yaml
{{ cookiecutter.project_name }}/Makefile
{{ cookiecutter.project_name }}/pyproject.toml

- Moving all `pre-commit` to local
N/A

Pre commit local

---

{{ cookiecutter.project_name }}/pyproject.toml

:arrow_up: update `rich`

---

.gitignore
poetry.lock
pyproject.toml
setup.cfg
{{ cookiecutter.project_name }}/.dockerignore
{{ cookiecutter.project_name }}/.gitignore
{{ cookiecutter.project_name }}/pyproject.toml

Settings update

---

{{ cookiecutter.project_name }}/cookiecutter-config-file.yml

Just fixed a small typo "THis" to "This"

Small typo fix

---

.dependabot/config.yml
Makefile
{{ cookiecutter.project_name }}/.dependabot/config.yml
{{ cookiecutter.project_name }}/Makefile

Improvements:
- bump dependabot from version 1 to 2
Fixes:
- Running `pip check` inside `poetry` virtual environment while checking safety in `Makefile`
- resolve TODO in `**/.dependabot/config.yml`

:arrow_up: using dependabot of version 2 and running `pip check` with poetry

---

Makefile
{{ cookiecutter.project_name }}/Makefile
{{ cookiecutter.project_name }}/docker/Dockerfile

Use latest poetry installer, see [README](https://github.com/python-poetry/poetry#updating-poetry).
Fixes:
```bash
This installer is deprecated. Poetry versions installed using this script will not be able to use 'self update' command to upgrade to 1.2.0a1 or later.
```

Use latest poetry installer

---

.github/workflows/build.yml
README.md
cookiecutter.json
{{ cookiecutter.project_name }}/.github/workflows/build.yml
{{ cookiecutter.project_name }}/.pre-commit-config.yaml
{{ cookiecutter.project_name }}/Makefile
{{ cookiecutter.project_name }}/README.md
{{ cookiecutter.project_name }}/cookiecutter-config-file.yml
{{ cookiecutter.project_name }}/docker/Dockerfile
{{ cookiecutter.project_name }}/pyproject.toml

Now you may choose a minimal python version (`3.7`, `3.8` or `3.9`)

🐍 Added minimal python version variable

---

README.md
cookiecutter.json
hooks/pre_gen_project.py
pyproject.toml
{{ cookiecutter.project_name }}/cookiecutter-config-file.yml
{{ cookiecutter.project_name }}/pyproject.toml

Now you may choose max length for formatters

📏 Added line length param

---

README.md
cookiecutter.json
{{ cookiecutter.project_name }}/pyproject.toml

- `classifiers` in pyproject.toml updated

🧩 Added licence and programming version generator

---

Makefile
{{ cookiecutter.project_name }}/Makefile
{{ cookiecutter.project_name }}/pyproject.toml
{{ cookiecutter.project_name }}/tests/test_example/test_hello.py
{{ cookiecutter.project_name }}/{{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_') }}/__init__.py
{{ cookiecutter.project_name }}/{{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_') }}/__main__.py

Updated example

---

Makefile
hooks/pre_gen_project.py
{{ cookiecutter.project_name }}/Makefile

🔎 Added semantic version validation

---

README.md
hooks/post_gen_project.py
poetry.lock
pyproject.toml
requirements.txt
{{ cookiecutter.project_name }}/_licences/apache.txt
{{ cookiecutter.project_name }}/_licences/bsd3.txt
{{ cookiecutter.project_name }}/_licences/gpl3.txt
{{ cookiecutter.project_name }}/_licences/mit.txt

😎 Removed `lice` dependency

---

README.md
pyproject.toml
{{ cookiecutter.project_name }}/Makefile

Fix for #311 where darlint incorrectly checks `.venv`

Fixes for issues #311

---

poetry.lock
pyproject.toml
requirements.txt
{{ cookiecutter.project_name }}/pyproject.toml

Update pyupgrade deps

---

README.md
pyproject.toml
{{ cookiecutter.project_name }}/Makefile

- Fixed `make check-safety`
- #311

🙈 Fix Makefile again

---

poetry.lock
pyproject.toml
{{ cookiecutter.project_name }}/pyproject.toml

⬆️ Update rich

---

Makefile
pyproject.toml
{{ cookiecutter.project_name }}/Makefile

Mypy fix in Makefile

---

Makefile
README.md
pyproject.toml
{{ cookiecutter.project_name }}/Makefile

- Important fix for `mypy installation`

😦 mypy install types fixes

---

poetry.lock
{{ cookiecutter.project_name }}/.github/dependabot.yml

📈fix docker in dependabot

---

pyproject.toml
{{ cookiecutter.project_name }}/pyproject.toml

updated pyupgrade
